# model_name_or_path: /home/toolkit/snapshots/fa0277d307db882ff9735fe0edc03cfb24a59442/dpo_pythia410m_tldr
save_generations: True
dataset_name: trl-lib/tldr
dataset_test_split: validation
max_new_tokens: 128
temperature: 0.010001
torch_dtype: bfloat16
# generate_batch_size: 16
# gen_dtype: float16
